<a href="https://colab.research.google.com/github/vasion9/Python451VS/blob/main/hw01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW 01

### Q1. Write a program to input your age and print whether you are more than or less than a billion seconds old.

In [ ]:
def years_to_seconds(years):
  days_per_year = 365.25
  hours_per_day = 24
  minutes_per_hour = 60
  seconds_per_minute = 60
  # The following line was indented to be within the function scope
  seconds = years * days_per_year * hours_per_day * minutes_per_hour * seconds_per_minute
  return seconds

age = int(input("Enter your age: "))

age_in_seconds = years_to_seconds(age)

one_billion_seconds = 1_000_000_000

if age_in_seconds > one_billion_seconds:
    print("You are more than a billion seconds old!")
else:
    print("You are less than a billion seconds old.")


Enter your age: 25
You are less than a billion seconds old.


### Q2. Create a list with 10 names. Print each name with a Good morning greeting with the name using a conditional loop.

For example

`name = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']`

Outputs will be 'Good morning, Ashley', 'Good morning, Brianna', and so on.

In [ ]:
names = ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank", "Grace", "Hank", "Ivy", "Jack"]

for name in names:
  print(f"Good morning, {name}!")



Good morning, Alice!
Good morning, Bob!
Good morning, Charlie!
Good morning, Diana!
Good morning, Eve!
Good morning, Frank!
Good morning, Grace!
Good morning, Hank!
Good morning, Ivy!
Good morning, Jack!


### Q3. Create a list of 15 numbers. Print only those numbers that are divisible by 2.

In [ ]:
numbers = [3, 8, 12, 15, 20, 22, 25, 30, 33, 36, 40, 45, 50, 55, 60]
for number in numbers:
  if number % 2 == 0:
    print(number)



8
12
20
22
30
36
40
50
60


### Q4. Print the squared numbers of a list containing at least 10 numbers with a mix of float, integer, and negative numbers. Use the longer method as well as list comprehension.

You can either generate your own list of 10 numbers or find use a random number generator.

In [ ]:
## Enter answer here.

nums = [0,-1.25,15.86,-25]
method1_squares = []

for i in nums:
    method1_squares.append(i**2)

print(method1_squares)

## Now method 2
numbers = [4, -3, 2.5, 7, -1.2, 0, 10, -5, 3.7, 6]

squared_numbers_long = []
for number in numbers:
    squared_numbers_long.append(number ** 2)

print("Squared numbers (using for loop):", squared_numbers_long)

squared_numbers_comp = [number ** 2 for number in numbers]

print("Squared numbers (using list comprehension):", squared_numbers_comp)

[0, 1.5625, 251.53959999999998, 625]
Squared numbers (using for loop): [16, 9, 6.25, 49, 1.44, 0, 100, 25, 13.690000000000001, 36]
Squared numbers (using list comprehension): [16, 9, 6.25, 49, 1.44, 0, 100, 25, 13.690000000000001, 36]


### Q5. Write a program to print a year if it is a leap year.

In [ ]:
year = int(input())

if year%4 == 0:
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

2025
2025 is not a leap year


### Q6. Use list comprensions to print all names in a list in upper case.

In [ ]:
names = ["Alice", "Bob", "Charlie", "Diana", "Eve", "Frank", "Grace", "Hank", "Ivy", "Jack"]

uppercase_names = [name.upper() for name in names]

print(uppercase_names)

['ALICE', 'BOB', 'CHARLIE', 'DIANA', 'EVE', 'FRANK', 'GRACE', 'HANK', 'IVY', 'JACK']


### Q7. Question on NUMPY arrays:

a. Create a numpy array called `original` with 100 random numbers. What is the largest number, smallest number, max, min, median, and standard deviation of your array? Print them.

HINT: use `np.random.uniform()`. Check online for the correct syntax. `np.random.rand(100)` will give you 100 random numbers of uniform distribution with mean 0 and standard deviation of 1, while we want a mix of larger numbers/integers.

b. Now create an array called `orig_sqrt` which contains the square roots of the numbers in the original array.

### Q8.  Converting 1D arrays into 2D arrays.

a. Convert your original array of 100 random numbers into a 2-dimensional array called `mat_array` with 20 rows and 5 columns. Print this array.

b. What is the mean of every column in `mat_array`?

c. What is the sum of every row? Create a list of 20 elements that contains the sum of every row in `mat_array`.

d. Create the transpose of `mat_array` and call it `transpose_array`. What are the dimensions of this array now? Again, find the mean of each column and the sum of each row.

### Q9. Array slicing:

a. create a new array which contains the 3rd-10th rows and all columns of `mat_array`. Print.

b. Print a new array which contains the the last 5 rows and the last 2 columns of `mat_array`. What is the dimension of this array?

c. Print a new array which contains the first 3 rows and last 10 columns of `transpose_array`.

In [ ]:
# Write your answer here. Feel free to break your answer into different blocks of code rather than using just this one cell. Label your answer neatly.
import numpy as np

original = np.random.uniform(0, 100, 100)

largest_number = np.max(original)
smallest_number = np.min(original)
max_value = np.max(original)  # Same as largest number
min_value = np.min(original)  # Same as smallest number
median_value = np.median(original)
std_deviation = np.std(original)

print("Largest number:", largest_number)
print("Smallest number:", smallest_number)
print("Max value:", max_value)
print("Min value:", min_value)
print("Median value:", median_value)
print("Standard deviation:", std_deviation)

orig_sqrt = np.sqrt(original)

print("Square Roots Array (orig_sqrt):", orig_sqrt)





Largest number: 99.38898438238145
Smallest number: 1.3861858357028245
Max value: 99.38898438238145
Min value: 1.3861858357028245
Median value: 47.57329735371185
Standard deviation: 28.793059549576434
Square Roots Array (orig_sqrt): [8.61649377 8.14778277 4.66002548 9.06616617 3.98835607 8.54693084
 8.61228921 5.63117238 5.50351971 8.27172593 8.78510778 9.24847516
 8.06828688 5.85907055 5.19122104 7.96002499 9.09835823 8.5474259
 6.24081373 4.07872416 4.85643398 5.26437385 1.17736394 6.18179729
 4.27406096 7.09654778 6.704304   6.94146418 6.22779574 5.47459895
 6.85293147 9.93817896 7.65351547 8.56273702 6.62521901 9.62965499
 7.66041136 8.75132333 5.77919733 7.23455007 5.12835691 8.77305244
 5.5979329  2.89844172 8.47824743 5.01964425 9.58756479 4.24285118
 5.33756373 9.07999181 9.89236326 9.57734188 7.27282817 3.95793078
 2.32702636 8.92374464 3.35017058 7.22069198 2.31393437 9.10660497
 7.33818002 9.87306765 2.38371679 8.39539419 9.59748514 4.47820076
 4.78988699 6.73231781 2.6780306

In [ ]:
import numpy as np

original = np.random.uniform(0, 100, 100)

mat_array = original.reshape(20, 5)

print("2D Array (mat_array):")
print(mat_array)

column_means = np.mean(mat_array, axis=0)

print("Mean of every column:")
print(column_means)

row_sums = np.sum(mat_array, axis=1)

row_sums_list = row_sums.tolist()

print("Sum of every row:")
print(row_sums_list)

transpose_array = mat_array.T

print("Transpose Array (transpose_array):")
print(transpose_array)
print("Dimensions of transpose_array:", transpose_array.shape)

transpose_column_means = np.mean(transpose_array, axis=0)

transpose_row_sums = np.sum(transpose_array, axis=1)

print("Mean of every column in transpose_array:")
print(transpose_column_means)
print("Sum of every row in transpose_array:")
print(transpose_row_sums)

2D Array (mat_array):
[[71.41372587 28.53821694 29.24030947 45.77082003  8.79351262]
 [71.57143667 83.79267074 19.48923633 43.61204195 49.25447089]
 [56.68446046 20.13114988 56.4076322  67.27105838 43.49101508]
 [ 4.26022066  6.25920024  8.55850898  4.8815954  74.51641252]
 [78.82462068 40.63976151 91.06647363 77.46755937 52.13039833]
 [49.62066604 48.97953524 14.87584523 50.15536038 49.19624714]
 [67.84010559 78.5406989  29.55699171 84.23807669 36.58337412]
 [96.84164716 54.59464133 32.60706398 57.67566544 93.6812861 ]
 [79.1186448  77.62939274 87.58161685  5.53189865 98.83912411]
 [62.82371248 24.53590686 19.70581308 40.41267026 71.83024155]
 [30.1106449  27.69061161 31.83941805 67.13911323 92.12215215]
 [40.49292004 69.45393349 12.60635909 73.90044349 42.34693484]
 [11.42709985 87.05289306 34.10847035 59.7582173  76.64188837]
 [45.90241404 95.41170708  0.25356881 67.85860033 20.11445206]
 [85.49478589 22.51954252  9.85740002 28.52123581 93.52802239]
 [60.82332547 81.63313969 37.3949

In [ ]:
import numpy as np

original = np.random.uniform(0, 100, 100)

mat_array = original.reshape(20, 5)

sliced_array_a = mat_array[2:10, :]

print("Sliced Array (3rd-10th rows, all columns):")
print(sliced_array_a)

sliced_array_b = mat_array[-5:, -2:]

print("Sliced Array (last 5 rows, last 2 columns):")
print(sliced_array_b)
print("Dimensions of sliced_array_b:", sliced_array_b.shape)

transpose_array = mat_array.T

sliced_array_c = transpose_array[:3, -10:]

print("Sliced Array (first 3 rows, last 10 columns of transpose_array):")
print(sliced_array_c)

Sliced Array (3rd-10th rows, all columns):
[[3.53619296e+00 5.36953148e+01 7.71250945e+01 8.35705524e+01
  9.87830613e+01]
 [7.83169885e-01 3.86729767e+01 6.07993078e+01 6.37197799e+01
  3.05594059e+01]
 [4.16679822e+01 6.17591800e+01 5.98451257e+01 7.60827214e+01
  8.22417674e+00]
 [9.20117702e+01 3.28169768e+01 4.67450870e+01 4.63060115e+01
  1.99458769e+01]
 [1.92755419e+01 9.24561776e+00 4.63171489e+01 5.50287676e+01
  8.62859761e+01]
 [9.37892333e+01 1.96851582e+01 5.06015935e+01 7.54828837e+01
  7.80722331e+01]
 [9.21832657e+01 2.77817449e+01 8.90444645e+01 7.51162476e-02
  7.15420231e+01]
 [7.79400270e+01 5.09483257e+01 6.41480469e+01 7.11247029e+01
  2.90688001e+01]]
Sliced Array (last 5 rows, last 2 columns):
[[95.2131832   3.74185593]
 [78.94155088 20.74086923]
 [41.01838458 94.73178282]
 [64.36618998  4.32482275]
 [20.03371264 49.03779428]]
Dimensions of sliced_array_b: (5, 2)
Sliced Array (first 3 rows, last 10 columns of transpose_array):
[[16.90134702  0.67084033 52.48740

### Q10. Assume you are inviting 15 friends to your party. You guest list has the following dietary preference.

`diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto, 'vegetarian', 'vegan']`

Their ages are as follows:

`age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]`

Create a list called `menu` which will contain 'veg. fried rice with whiskey' for vegans and vegetarians aged 21 and above,  'veg. fried rice with mocktail' for vegans and vegetarians aged below 21. Follow the same logic and assign fish and white wine to pescetarians of legal age (and fish with mocktail to those below 21). Keto and omnivore guests above 21 will have 'steak and red wine'. Complete the series with the appropriate drink for underage guests.

In [ ]:
# Write your answer here.
import numpy as np

diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto', 'vegetarian', 'vegan']
age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]

menu = []

for i in range(len(diet)):
    if diet[i] in ['vegan', 'vegetarian']:
        if age[i] >= 21:
            menu.append('veg. fried rice with whiskey')
        else:
            menu.append('veg. fried rice with mocktail')
    elif diet[i] == 'pescetarian':
        if age[i] >= 21:
            menu.append('fish and white wine')
        else:
            menu.append('fish with mocktail')
    elif diet[i] in ['keto', 'omnivore']:
        if age[i] >= 21:
            menu.append('steak and red wine')
        else:
            menu.append('steak with mocktail')

print("Menu for each guest:")
for i, item in enumerate(menu):
    print(f"Guest {i+1}: {item}")



Menu for each guest:
Guest 1: veg. fried rice with whiskey
Guest 2: fish with mocktail
Guest 3: veg. fried rice with mocktail
Guest 4: steak and red wine
Guest 5: fish and white wine
Guest 6: steak with mocktail
Guest 7: steak and red wine
Guest 8: veg. fried rice with whiskey
Guest 9: steak with mocktail
Guest 10: steak and red wine
Guest 11: veg. fried rice with mocktail
Guest 12: steak with mocktail
Guest 13: steak and red wine
Guest 14: veg. fried rice with whiskey
Guest 15: veg. fried rice with whiskey
